--liquibase formatted sql
--changeset mazella:01
create TABLE TSK.TASK(
    ID SERIAL PRIMARY KEY,
    CREATION_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    POINTS INTEGER NOT NULL
);
--rollback DROP TABLE TSK.TASK;