spring:
  liquibase:
    url: jdbc:postgresql://postgres:5432/tasks
    drop-first: false
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/tasks
    username: postgres
    password: postgres
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin