INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'PENDING', 'Implement serializer of Task class', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'PENDING', 'Create a wrapper class of Task cass', 1);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'PENDING', 'Implement desserializer of Task class', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-06-18 12:00:00', 'COMPLETED', 'Create controller to aggregate Task class', 1);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'COMPLETED', 'Create endpoint to retrieve information from Task by id', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'COMPLETED', 'Create endpoint to delete information from Task by id', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'COMPLETED', 'Create endpoint to change information from Task by id', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-01-07 12:00:00', 'PENDING', 'Create endpoint to list information from Task', 3);
INSERT INTO TSK.TASK(CREATION_DATE, STATUS, DESCRIPTION, POINTS) VALUES ('2019-06-15 12:00:00', 'PENDING', 'Create controller advice handle application exception', 5);