CREATE SCHEMA TSK;

CREATE SEQUENCE TSK.SEQ_TASK;
CREATE TABLE TSK.TASK(
    ID BIGINT DEFAULT TSK.SEQ_TASK.NEXTVAL PRIMARY KEY,
    CREATION_DATE TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    POINTS INTEGER NOT NULL
);